2024-06-24 12:18:46,575 ERROR: Exception on /nba [GET] [in C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\app\routes.py", line 205, in nba
    return render_template('nba.html', title='NBA')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\app\templates\nba.html", line 4, in top-level template code
    {% from nba_api.stats.endpoints import playercareerstats %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\venv\Lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'nba_api' is undefined
2024-06-24 12:18:52,548 INFO: Microblog Startup [in C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\app\__init__.py:49]
2024-06-24 12:19:23,422 INFO: Microblog Startup [in C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\app\__init__.py:49]
2024-06-24 12:21:23,407 INFO: Microblog Startup [in C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\app\__init__.py:49]
2024-06-24 12:23:32,043 INFO: Microblog Startup [in C:\Users\hazab\Desktop\CodeProjects\GitHubRepos\FlaskApp_GitHub\FlaskWebsite\app\__init__.py:49]
